export enum ETaskType {
  TELEGRAM_TASK = "TELEGRAM_TASK",
  X_TASK = "X_TASK",
  YOUTUBE_TASK = "YOUTUBE_TASK",
  DISCORD_TASK = "DISCORD_TASK",
  TIKTOK_TASK = "TIKTOK_TASK",
  INSTAGRAM_TASK = "INSTAGRAM_TASK",
  FACEBOOK_TASK = "FACEBOOK_TASK",
}

export enum EUserTaskStatus {
  UNCLAIMED = "UNCLAIMED",
  PENDING = "PENDING",
  READY_TO_CLAIM = "READY_TO_CLAIM",
  CLAIMED = "CLAIMED",
}

export enum ETaskAPIType {
  NONE = "NONE",
  TELEGRAM_API = "TELEGRAM_API",
  X_API = "X_API",
}
