export enum ETaskType {
  TELEGRAM_TASK = "TELEGRAM_TASK",
  X_TASK = "X_TASK",
  YOUTUBE_TASK = "YOUTUBE_TASK",
  DISCORD_TASK = "DISCORD_TASK",
  TIKTOK_TASK = "TIKTOK_TASK",
  INSTAGRAM_TASK = "INSTAGRAM_TASK",
  FACEBOOK_TASK = "FACEBOOK_TASK",
}

export enum EUserTaskStatus {
  UNCLAIMED = "UNCLAIMED",
  PENDING = "PENDING",
  READY_TO_CLAIM = "READY_TO_CLAIM",
  CLAIMED = "CLAIMED",
}

export enum ETaskAPIType {
  NONE = "NONE",
  TELEGRAM_API = "TELEGRAM_API",
  X_API = "X_API",
}

export enum EMinerLevel {
  LEVEL_1 = "LEVEL_1",
  LEVEL_2 = "LEVEL_2",
  LEVEL_3 = "LEVEL_3",
  LEVEL_4 = "LEVEL_4",
  LEVEL_5 = "LEVEL_5",
}

export enum EHiltiLevel {
  LEVEL_1 = "LEVEL_1",
  LEVEL_2 = "LEVEL_2",
  LEVEL_3 = "LEVEL_3",
  LEVEL_4 = "LEVEL_4",
  LEVEL_5 = "LEVEL_5",
}
